# Anna KaRNNa

In this notebook, we'll build a character-wise RNN trained on Anna Karenina, one of my all-time favorite books. It'll be able to generate new text based on the text from the book.

This network is based off of Andrej Karpathy's [post on RNNs](http://karpathy.github.io/2015/05/21/rnn-effectiveness/) and [implementation in Torch](https://github.com/karpathy/char-rnn). Also, some information [here at r2rt](http://r2rt.com/recurrent-neural-networks-in-tensorflow-ii.html) and from [Sherjil Ozair](https://github.com/sherjilozair/char-rnn-tensorflow) on GitHub. Below is the general architecture of the character-wise RNN.

<img src="assets/charseq.jpeg" width="500">

In [1]:
import time
from collections import namedtuple

import numpy as np
import tensorflow as tf

First we'll load the text file and convert it into integers for our network to use. Here I'm creating a couple dictionaries to convert the characters to and from integers. Encoding the characters as integers makes it easier to use as input in the network.

In [2]:
with open('anna.txt', 'r') as f:
    text=f.read()

# set : 重複のない set オブジェクトを作成    
# sorted : ソートして、リストを作成
vocab = sorted(set(text))
# 辞書-1 の作成 : {文字 , ID}
vocab_to_int = {c: i for i, c in enumerate(vocab)}
# 辞書-2 の作成 : {ID , 文字}
int_to_vocab = dict(enumerate(vocab))
# textの内容を、辞書-1 で　数値に置き換える
encoded = np.array([vocab_to_int[c] for c in text], dtype=np.int32)

### 入力のチェック

In [3]:
print("【text】")
print( "type(text)   = ", type(text) )
print( "len(text)    = ", len(text))
print("text[200:300] = ", text[200:300])
print("--------------------------")
print("【vocab】")
print( "type(vocab)  = ", type(vocab) )
print( "len(vocab)   = ", len(vocab))
print( "vocab[70:80] = ", vocab[70:80])
print("--------------------------")
print("【vocab_to_int】")
print( "type(vocab_to_int)  = ", type(vocab_to_int) )
print( "len(vocab_to_int)   = ", len(vocab_to_int))
print( "vocab_to_int = ", vocab_to_int)
print("--------------------------")

【text】
type(text)   =  <class 'str'>
len(text)    =  1985223
text[200:300] =   an intrigue with a French
girl, who had been a governess in their family, and she had announced to

--------------------------
【vocab】
type(vocab)  =  <class 'list'>
len(vocab)   =  83
vocab[70:80] =  ['n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w']
--------------------------
【vocab_to_int】
type(vocab_to_int)  =  <class 'dict'>
len(vocab_to_int)   =  83
vocab_to_int =  {'\n': 0, ' ': 1, '!': 2, '"': 3, '$': 4, '%': 5, '&': 6, "'": 7, '(': 8, ')': 9, '*': 10, ',': 11, '-': 12, '.': 13, '/': 14, '0': 15, '1': 16, '2': 17, '3': 18, '4': 19, '5': 20, '6': 21, '7': 22, '8': 23, '9': 24, ':': 25, ';': 26, '?': 27, '@': 28, 'A': 29, 'B': 30, 'C': 31, 'D': 32, 'E': 33, 'F': 34, 'G': 35, 'H': 36, 'I': 37, 'J': 38, 'K': 39, 'L': 40, 'M': 41, 'N': 42, 'O': 43, 'P': 44, 'Q': 45, 'R': 46, 'S': 47, 'T': 48, 'U': 49, 'V': 50, 'W': 51, 'X': 52, 'Y': 53, 'Z': 54, '_': 55, '`': 56, 'a': 57, 'b': 58, 'c': 59, 'd': 60, 'e': 6

Let's check out the first 100 characters, make sure everything is peachy. According to the [American Book Review](http://americanbookreview.org/100bestlines.asp), this is the 6th best first line of a book ever.

In [4]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

And we can see the characters encoded as integers.

In [5]:
encoded[:100]

array([31, 64, 57, 72, 76, 61, 74,  1, 16,  0,  0,  0, 36, 57, 72, 72, 81,
        1, 62, 57, 69, 65, 68, 65, 61, 75,  1, 57, 74, 61,  1, 57, 68, 68,
        1, 57, 68, 65, 67, 61, 26,  1, 61, 78, 61, 74, 81,  1, 77, 70, 64,
       57, 72, 72, 81,  1, 62, 57, 69, 65, 68, 81,  1, 65, 75,  1, 77, 70,
       64, 57, 72, 72, 81,  1, 65, 70,  1, 65, 76, 75,  1, 71, 79, 70,  0,
       79, 57, 81, 13,  0,  0, 33, 78, 61, 74, 81, 76, 64, 65, 70])

Since the network is working with individual characters, it's similar to a classification problem in which we are trying to predict the next character from the previous text.  Here's how many 'classes' our network has to pick from.

In [6]:
len(vocab)

83

## Making training mini-batches

Here is where we'll make our mini-batches for training. Remember that we want our batches to be multiple sequences of some desired number of sequence steps. Considering a simple example, our batches would look like this:

<img src="assets/sequence_batching@1x.png" width=500px>


<br>

We start with our text encoded as integers in one long array in `encoded`. Let's create a function that will give us an iterator for our batches. I like using [generator functions](https://jeffknupp.com/blog/2013/04/07/improve-your-python-yield-and-generators-explained/) to do this. Then we can pass `encoded` into this function and get our batch generator.

The first thing we need to do is discard some of the text so we only have completely full batches. Each batch contains $N \times M$ characters, where $N$ is the batch size (the number of sequences) and $M$ is the number of steps. Then, to get the total number of batches, $K$, we can make from the array `arr`, you divide the length of `arr` by the number of characters per batch. Once you know the number of batches, you can get the total number of characters to keep from `arr`, $N * M * K$.

After that, we need to split `arr` into $N$ sequences. You can do this using `arr.reshape(size)` where `size` is a tuple containing the dimensions sizes of the reshaped array. We know we want $N$ sequences (`batch_size` below), let's make that the size of the first dimension. For the second dimension, you can use `-1` as a placeholder in the size, it'll fill up the array with the appropriate data for you. After this, you should have an array that is $N \times (M * K)$.

Now that we have this array, we can iterate through it to get our batches. The idea is each batch is a $N \times M$ window on the $N \times (M * K)$ array. For each subsequent batch, the window moves over by `n_steps`. We also want to create both the input and target arrays. Remember that the targets are the inputs shifted over one character. 

The way I like to do this window is use `range` to take steps of size `n_steps` from $0$ to `arr.shape[1]`, the total number of steps in each sequence. That way, the integers you get from `range` always point to the start of a batch, and each window is `n_steps` wide.

> **Exercise:** Write the code for creating batches in the function below. The exercises in this notebook _will not be easy_. I've provided a notebook with solutions alongside this notebook. If you get stuck, checkout the solutions. The most important thing is that you don't copy and paste the code into here, **type out the solution code yourself.**

In [7]:
def get_batches(arr, batch_size, n_steps):
    '''Create a generator that returns batches of size
       batch_size x n_steps from arr.
       
       Arguments
       ---------
       arr       : Array you want to make batches from
       batch_size: Batch size, the number of sequences per batch
       n_steps   : Number of sequence steps per batch
    '''
    # Get the number of characters per batch and number of batches we can make
    # 1回のバッチ処理で使用する文字数
    characters_per_batch = batch_size * n_steps
    # バッチ回数の取得 = 全データ数 / 1回のバッチ数（切り捨て除算）
    n_batches            = len(arr) // characters_per_batch
    
    # Keep only enough characters to make full batches
    # arr の中から、バッチ用データ数で割り切れる部分のみを抽出する
    arr = arr[ : n_batches * characters_per_batch ]
    
    # Reshape into batch_size rows
    # 行 = batch_size、　列 ≒ n_steps * n_batches　に　ReShape 
    arr = arr.reshape((batch_size, -1))
    
    for n in range(0, arr.shape[1], n_steps):
        # The features : 全行（バッチ分）× RNNの入力数分 のデータを取得
        x      = arr[ : ,       n : (n + n_steps) ]
        
        # The targets, shifted by one : 予測値用に1個未来のデータを取得
        y_temp = arr[ : , (n + 1) : (n + n_steps + 1) ]
        
        # 最後の行が、データ不足になるので、zerosで適切なサイズを確保し
        # データがある部分のみ上書きする
        # 最後の行以外は、 y_temp　と　y　のサイズは同じ
        y = np.zeros( x.shape , dtype = x.dtype )
        y[ : , : y_temp.shape[1] ] = y_temp        
        
        # For分の中で、yieldを使っている　⇒　出力は　generatorになる
        yield x, y

Now I'll make my data sets and we can check out what's going on here. Here I'm going to use a batch size of 10 and 50 sequence steps.

In [8]:
batch_size = 10
n_steps    = 50
batches    = get_batches(encoded, batch_size, n_steps)
# generator から　バッチ・データを取り出す
x, y       = next(batches)

In [9]:
print('encoded\n', encoded[:100])
print('x\n'   , x[:10, :10])
print('\ny\n' , y[:10, :10])

encoded
 [31 64 57 72 76 61 74  1 16  0  0  0 36 57 72 72 81  1 62 57 69 65 68 65
 61 75  1 57 74 61  1 57 68 68  1 57 68 65 67 61 26  1 61 78 61 74 81  1
 77 70 64 57 72 72 81  1 62 57 69 65 68 81  1 65 75  1 77 70 64 57 72 72
 81  1 65 70  1 65 76 75  1 71 79 70  0 79 57 81 13  0  0 33 78 61 74 81
 76 64 65 70]
x
 [[31 64 57 72 76 61 74  1 16  0]
 [ 1 57 69  1 70 71 76  1 63 71]
 [78 65 70 13  0  0  3 53 61 75]
 [70  1 60 77 74 65 70 63  1 64]
 [ 1 65 76  1 65 75 11  1 75 65]
 [ 1 37 76  1 79 57 75  0 71 70]
 [64 61 70  1 59 71 69 61  1 62]
 [26  1 58 77 76  1 70 71 79  1]
 [76  1 65 75 70  7 76 13  1 48]
 [ 1 75 57 65 60  1 76 71  1 64]]

y
 [[64 57 72 76 61 74  1 16  0  0]
 [57 69  1 70 71 76  1 63 71 65]
 [65 70 13  0  0  3 53 61 75 11]
 [ 1 60 77 74 65 70 63  1 64 65]
 [65 76  1 65 75 11  1 75 65 74]
 [37 76  1 79 57 75  0 71 70 68]
 [61 70  1 59 71 69 61  1 62 71]
 [ 1 58 77 76  1 70 71 79  1 75]
 [ 1 65 75 70  7 76 13  1 48 64]
 [75 57 65 60  1 76 71  1 64 61]]


If you implemented `get_batches` correctly, the above output should look something like 
```
x
 [[55 63 69 22  6 76 45  5 16 35]
 [ 5 69  1  5 12 52  6  5 56 52]
 [48 29 12 61 35 35  8 64 76 78]
 [12  5 24 39 45 29 12 56  5 63]
 [ 5 29  6  5 29 78 28  5 78 29]
 [ 5 13  6  5 36 69 78 35 52 12]
 [63 76 12  5 18 52  1 76  5 58]
 [34  5 73 39  6  5 12 52 36  5]
 [ 6  5 29 78 12 79  6 61  5 59]
 [ 5 78 69 29 24  5  6 52  5 63]]

y
 [[63 69 22  6 76 45  5 16 35 35]
 [69  1  5 12 52  6  5 56 52 29]
 [29 12 61 35 35  8 64 76 78 28]
 [ 5 24 39 45 29 12 56  5 63 29]
 [29  6  5 29 78 28  5 78 29 45]
 [13  6  5 36 69 78 35 52 12 43]
 [76 12  5 18 52  1 76  5 58 52]
 [ 5 73 39  6  5 12 52 36  5 78]
 [ 5 29 78 12 79  6 61  5 59 63]
 [78 69 29 24  5  6 52  5 63 76]]
 ```
 although the exact numbers will be different. Check to make sure the data is shifted over one step for `y`.

## Building the model

Below is where you'll build the network. We'll break it up into parts so it's easier to reason about each bit. Then we can connect them up into the whole network.

<img src="assets/charRNN.png" width=500px>


### Inputs

First off we'll create our input placeholders. As usual we need placeholders for the training data and the targets. We'll also create a placeholder for dropout layers called `keep_prob`. This will be a scalar, that is a 0-D tensor. To make a scalar, you create a placeholder without giving it a size.

> **Exercise:** Create the input placeholders in the function below.

In [10]:
def build_inputs(batch_size, num_steps):
    ''' Define placeholders for inputs, targets, and dropout 
    
        Arguments
        ---------
        batch_size: Batch size, number of sequences per batch
        num_steps: Number of sequence steps in a batch
        
    '''
    # Declare placeholders we'll feed into the graph
    # 引数 : tf.placeholder( dtype, shape=None, name=None )
    inputs  = tf.placeholder( tf.int32, [batch_size, num_steps], name='inputs' ) 
    targets = tf.placeholder( tf.int32, [batch_size, num_steps], name='targets') 
    
    # Keep probability placeholder for drop out layers
    keep_prob = tf.placeholder( tf.float32, name='keep_prob')
    
    return inputs, targets, keep_prob

### LSTM Cell

Here we will create the LSTM cell we'll use in the hidden layer. We'll use this cell as a building block for the RNN. So we aren't actually defining the RNN here, just the type of cell we'll use in the hidden layer.

We first create a basic LSTM cell with

```python
lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
```

where `num_units` is the number of units in the hidden layers in the cell. Then we can add dropout by wrapping it with 

```python
tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
```
You pass in a cell and it will automatically add dropout to the inputs or outputs. Finally, we can stack up the LSTM cells into layers with [`tf.contrib.rnn.MultiRNNCell`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/contrib/rnn/MultiRNNCell). With this, you pass in a list of cells and it will send the output of one cell into the next cell. Previously with TensorFlow 1.0, you could do this

```python
tf.contrib.rnn.MultiRNNCell([cell]*num_layers)
```

This might look a little weird if you know Python well because this will create a list of the same `cell` object. However, TensorFlow 1.0 will create different weight matrices for all `cell` objects. But, starting with TensorFlow 1.1 you actually need to create new cell objects in the list. To get it to work in TensorFlow 1.1, it should look like

```python
def build_cell(num_units, keep_prob):
    lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
    drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
    
    return drop
    
tf.contrib.rnn.MultiRNNCell([build_cell(num_units, keep_prob) for _ in range(num_layers)])
```

Even though this is actually multiple LSTM cells stacked on each other, you can treat the multiple layers as one cell.

We also need to create an initial cell state of all zeros. This can be done like so

```python
initial_state = cell.zero_state(batch_size, tf.float32)
```

Below, we implement the `build_lstm` function to create these LSTM cells and the initial state.

In [11]:
def build_lstm(lstm_size, num_layers, batch_size, keep_prob):
    ''' Build LSTM cell.
        < Arguments >
        keep_prob : Scalar tensor (tf.placeholder) for the dropout keep probability
        lstm_size : Size of the hidden layers in the LSTM cells
        num_layers: Number of LSTM layers
        batch_size: Batch size
    '''
    #---------------------------------------------------------------------#
    # 関数内　で　関数を定義する
    ### Build the LSTM Cell
    def build_cell(num_units, keep_prob):  
        # Use a basic LSTM cell
        # 引数として、隠れ層の数　を入力する
        lstm = tf.contrib.rnn.BasicLSTMCell(num_units=lstm_size)

        # Add dropout to the cell outputs
        # input　と　output　に　dropoutを追加する、dropoutのratioを入力
        drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
        
        return drop
    #---------------------------------------------------------------------#
    # Stack up multiple LSTM layers, for deep learning
    # 関数 build_cell で、LSTMを1セット　作成する。
    # num_layers　分だけ、for文で　LSTMセット　を追加する
    cell = tf.contrib.rnn.MultiRNNCell( [build_cell(lstm_size, keep_prob) for _ in range(num_layers)] )
    #cell = tf.contrib.rnn.MultiRNNCell( [build_cell(lstm_size, keep_prob)] * num_layers )
    # ゼロで初期化。不明なバッチ数を入力する
    initial_state = cell.zero_state(batch_size, tf.float32)
    
    return cell, initial_state

### RNN Output

Here we'll create the output layer. We need to connect the output of the RNN cells to a full connected layer with a softmax output. The softmax output gives us a probability distribution we can use to predict the next character, so we want this layer to have size $C$, the number of classes/characters we have in our text.

If our input has batch size $N$, number of steps $M$, and the hidden layer has $L$ hidden units, then the output is a 3D tensor with size $N \times M \times L$. The output of each LSTM cell has size $L$, we have $M$ of them, one for each sequence step, and we have $N$ sequences. So the total size is $N \times M \times L$. 

We are using the same fully connected layer, the same weights, for each of the outputs. Then, to make things easier, we should reshape the outputs into a 2D tensor with shape $(M * N) \times L$. That is, one row for each sequence and step, where the values of each row are the output from the LSTM cells. We get the LSTM output as a list, `lstm_output`. First we need to concatenate this whole list into one array with [`tf.concat`](https://www.tensorflow.org/api_docs/python/tf/concat). Then, reshape it (with `tf.reshape`) to size $(M * N) \times L$.

One we have the outputs reshaped, we can do the matrix multiplication with the weights. We need to wrap the weight and bias variables in a variable scope with `tf.variable_scope(scope_name)` because there are weights being created in the LSTM cells. TensorFlow will throw an error if the weights created here have the same names as the weights created in the LSTM cells, which they will be default. To avoid this, we wrap the variables in a variable scope so we can give them unique names.

> **Exercise:** Implement the output layer in the function below.

In [12]:
def build_output(lstm_output, in_size, out_size, flag_debug=1):
    ''' Build a softmax layer, return the softmax output and logits.
        <Arguments>
        lstm_output : List of output tensors from the LSTM layer
        in_size     : Size of the input tensor, for example, size of the LSTM cells
        out_size    : Size of this softmax layer
    '''
    # Reshape output so it's a bunch of rows, one row for each step for each sequence.
    # Concatenate lstm_output over axis 1 (the columns)
    # lstm_output.shape = [ batch_size, num_steps, lstm_size ]
    # ??? concatへの入力データが1個であるため、 入力＝出力　になっている
    seq_output = tf.concat( lstm_output, 1)

    # Reshape seq_output to a 2D tensor with lstm_size columns
    # x.shape = [ (batch_size * num_steps) , lstm_size(=in_size)  ]
    x = tf.reshape( seq_output, [-1, in_size])
    
    # Connect the RNN outputs to a softmax layer
    with tf.variable_scope('softmax'):
        # Create the weight and bias variables here
        # in_size  = lstm_size
        # out_size = テキスト中のクラス数
        softmax_w = tf.Variable(tf.truncated_normal((in_size, out_size), stddev=0.1))
        softmax_b = tf.Variable(tf.zeros(out_size))
    
    # Since output is a bunch of rows of RNN cell outputs, logits will be a bunch
    # of rows of logit outputs, one for each step and sequence
    # logits.shape = [ (batch_size * num_steps) , クラス数 ] 
    logits = tf.matmul(x, softmax_w) + softmax_b
    
    # Use softmax to get the probabilities for predicted characters
    # out.shape = [ (batch_size * num_steps) , クラス数 ] 
    out = tf.nn.softmax(logits, name='predictions')
    
    #-------------------------------------------------------------
    if flag_debug:
        print("---------------------------------------------------")
        print("<def build_output>")
        print("------------------")
        print("lstm_output.shape = ", lstm_output.shape)
        print("seq_output.shape  = ", seq_output.shape) 
        print("x.shape           = ", x.shape)
        print("softmax_w.shape   = ", softmax_w.shape)
        print("softmax_b.shape   = ", softmax_b.shape)
        print("logits.shape      = ", logits.shape)
        print("out.shape         = ", out.shape)
        print("------------------")
    #-------------------------------------------------------------

    return out, logits

### Training loss

Next up is the training loss. We get the logits and targets and calculate the softmax cross-entropy loss. First we need to one-hot encode the targets, we're getting them as encoded characters. Then, reshape the one-hot targets so it's a 2D tensor with size $(M*N) \times C$ where $C$ is the number of classes/characters we have. Remember that we reshaped the LSTM outputs and ran them through a fully connected layer with $C$ units. So our logits will also have size $(M*N) \times C$.

Then we run the logits and targets through `tf.nn.softmax_cross_entropy_with_logits` and find the mean to get the loss.

>**Exercise:** Implement the loss calculation in the function below.

In [13]:
def build_loss(logits, targets, lstm_size, num_classes, flag_debug=1):
    ''' Calculate the loss from the logits and the targets.
        <Arguments>
        logits: Logits from final fully connected layer
        targets: Targets for supervised learning
        lstm_size: Number of LSTM hidden units
        num_classes: Number of classes in targets
    '''
    # One-hot encode targets and reshape to match logits, one row per sequence per step
    # y_one_hot.shape = [ batch_size, num_steps, クラス数 ]
    y_one_hot  = tf.one_hot(targets, num_classes)
    
    # y_reshaped.shape = [ (batch_size * num_steps) , クラス数 ] 
    y_reshaped = tf.reshape(y_one_hot, logits.get_shape())
    
    # Softmax cross entropy loss
    loss = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y_reshaped)
    # reduce_mean　で　axisを指定しないときは、全データの平均（スカラー）を出力
    loss = tf.reduce_mean(loss)
    
    #-------------------------------------------------------------
    if flag_debug:
        print("---------------------------------------------------")
        print("<def build_loss>")
        print("------------------")
        print("y_one_hot.shape    = ", y_one_hot.shape)
        print("y_reshaped.shape   = ", y_reshaped.shape)
        print("logits.get_shape() = ", logits.get_shape())
        print("loss.shape         = ", loss.shape)
        print("------------------")
    #-------------------------------------------------------------    
    
    return loss

### Optimizer

Here we build the optimizer. Normal RNNs have have issues gradients exploding and disappearing. LSTMs fix the disappearance problem, but the gradients can still grow without bound. To fix this, we can clip the gradients above some threshold. That is, if a gradient is larger than that threshold, we set it to the threshold. This will ensure the gradients never grow overly large. Then we use an AdamOptimizer for the learning step.

In [14]:
def build_optimizer(loss, learning_rate, grad_clip):
    ''' Build optmizer for training, using gradient clipping.
        <Arguments>
        loss          : Network loss
        learning_rate : Learning rate for optimizer
    '''
    # Optimizer for training, using gradient clipping to control exploding gradients
    
    # trainable=True の変数を作成
    tvars     = tf.trainable_variables()
    
    # gradient の計算値　に　clip を適用する
    grads, _  = tf.clip_by_global_norm(tf.gradients(loss, tvars), grad_clip)
    
    # Adam Optimizer オブジェクトを作成　with learning_rate
    train_op  = tf.train.AdamOptimizer(learning_rate)
    
    # Adam Optimizer オブジェクト に gradient と trainable variable　を入力
    optimizer = train_op.apply_gradients(zip(grads, tvars))
    
    return optimizer

### Build the network

Now we can put all the pieces together and build a class for the network. To actually run data through the LSTM cells, we will use [`tf.nn.dynamic_rnn`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/nn/dynamic_rnn). This function will pass the hidden and cell states across LSTM cells appropriately for us. It returns the outputs for each LSTM cell at each step for each sequence in the mini-batch. It also gives us the final LSTM state. We want to save this state as `final_state` so we can pass it to the first LSTM cell in the the next mini-batch run. For `tf.nn.dynamic_rnn`, we pass in the cell and initial state we get from `build_lstm`, as well as our input sequences. Also, we need to one-hot encode the inputs before going into the RNN. 

> **Exercise:** Use the functions you've implemented previously and `tf.nn.dynamic_rnn` to build the network.

In [15]:
class CharRNN:
    def __init__(self, num_classes, batch_size=64, num_steps=50, 
                       lstm_size=128, num_layers=2, learning_rate=0.001, 
                       grad_clip=5, sampling=False):
    
        # When we're using this network for sampling later, we'll be passing in
        # one character at a time, so providing an option for that
        # のちの機能拡張のために、オプションを用意
        if sampling == True:
            batch_size, num_steps = 1, 1
        else:
            batch_size, num_steps = batch_size, num_steps

        # 計算グラフのリセット
        tf.reset_default_graph()
        
        # Build the input placeholder tensors, 入力データの作成
        self.inputs, self.targets, self.keep_prob = build_inputs(batch_size, num_steps)

        # Build the LSTM cell, LSTMモデルの作成
        cell, self.initial_state = build_lstm(lstm_size, num_layers, batch_size, self.keep_prob)

        ### Run the data through the RNN layers
        # First, one-hot encode the input tokens, 入力の　One-Hot化
        x_one_hot = tf.one_hot(self.inputs, num_classes)
        
        # Run each sequence step through the RNN with tf.nn.dynamic_rnn
        # 可変長RNNの実装
        outputs, state   = tf.nn.dynamic_rnn(cell, x_one_hot, initial_state=self.initial_state)
        self.final_state = state
        
        # Get softmax predictions and logits
        # 出力を reshape して、softmax_with_loss の適用
        self.prediction, self.logits = build_output(outputs, lstm_size, num_classes)
        
        # Loss and optimizer (with gradient clipping)
        # loss　の　平均値を計算
        self.loss      = build_loss(self.logits, self.targets, lstm_size, num_classes)
        # gradient の計算
        self.optimizer = build_optimizer(self.loss, learning_rate, grad_clip)

## Hyperparameters

Here are the hyperparameters for the network.

* `batch_size` - Number of sequences running through the network in one pass.
* `num_steps` - Number of characters in the sequence the network is trained on. Larger is better typically, the network will learn more long range dependencies. But it takes longer to train. 100 is typically a good number here.
* `lstm_size` - The number of units in the hidden layers.
* `num_layers` - Number of hidden LSTM layers to use
* `learning_rate` - Learning rate for training
* `keep_prob` - The dropout keep probability when training. If you're network is overfitting, try decreasing this.

Here's some good advice from Andrej Karpathy on training the network. I'm going to copy it in here for your benefit, but also link to [where it originally came from](https://github.com/karpathy/char-rnn#tips-and-tricks).

> ## Tips and Tricks

>### Monitoring Validation Loss vs. Training Loss
>If you're somewhat new to Machine Learning or Neural Networks it can take a bit of expertise to get good models. The most important quantity to keep track of is the difference between your training loss (printed during training) and the validation loss (printed once in a while when the RNN is run on the validation data (by default every 1000 iterations)). In particular:

> - If your training loss is much lower than validation loss then this means the network might be **overfitting**. Solutions to this are to decrease your network size, or to increase dropout. For example you could try dropout of 0.5 and so on.
> - If your training/validation loss are about equal then your model is **underfitting**. Increase the size of your model (either number of layers or the raw number of neurons per layer)

> ### Approximate number of parameters

> The two most important parameters that control the model are `lstm_size` and `num_layers`. I would advise that you always use `num_layers` of either 2/3. The `lstm_size` can be adjusted based on how much data you have. The two important quantities to keep track of here are:

> - The number of parameters in your model. This is printed when you start training.
> - The size of your dataset. 1MB file is approximately 1 million characters.

>These two should be about the same order of magnitude. It's a little tricky to tell. Here are some examples:

> - I have a 100MB dataset and I'm using the default parameter settings (which currently print 150K parameters). My data size is significantly larger (100 mil >> 0.15 mil), so I expect to heavily underfit. I am thinking I can comfortably afford to make `lstm_size` larger.
> - I have a 10MB dataset and running a 10 million parameter model. I'm slightly nervous and I'm carefully monitoring my validation loss. If it's larger than my training loss then I may want to try to increase dropout a bit and see if that helps the validation loss.

> ### Best models strategy

>The winning strategy to obtaining very good models (if you have the compute time) is to always err on making the network larger (as large as you're willing to wait for it to compute) and then try different dropout values (between 0,1). Whatever model has the best validation performance (the loss, written in the checkpoint filename, low is good) is the one you should use in the end.

>It is very common in deep learning to run many different models with many different hyperparameter settings, and in the end take whatever checkpoint gave the best validation performance.

>By the way, the size of your training and validation splits are also parameters. Make sure you have a decent amount of data in your validation set or otherwise the validation performance will be noisy and not very informative.

In [16]:
batch_size    = 200   # Sequences per batch
num_steps     = 100   # Number of sequence steps per batch
lstm_size     = 512   # Size of hidden layers in LSTMs
num_layers    = 2     # Number of LSTM layers
learning_rate = 0.001 # Learning rate
keep_prob     = 0.5   # Dropout keep probability

## Time for training

This is typical training code, passing inputs and targets into the network, then running the optimizer. Here we also get back the final LSTM state for the mini-batch. Then, we pass that state back into the network so the next batch can continue the state from the previous batch. And every so often (set by `save_every_n`) I save a checkpoint.

Here I'm saving checkpoints with the format

`i{iteration number}_l{# hidden layer units}.ckpt`

> **Exercise:** Set the hyperparameters above to train the network. Watch the training loss, it should be consistently dropping. Also, I highly advise running this on a GPU.

In [17]:
epochs = 20

# Print losses every N interations
print_every_n = 50

# Save every N iterations
save_every_n = 200

model = CharRNN(len(vocab), batch_size=batch_size, num_steps=num_steps,
                lstm_size=lstm_size, num_layers=num_layers, 
                learning_rate=learning_rate)

saver = tf.train.Saver(max_to_keep=100)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    # Use the line below to load a checkpoint and resume training
    #saver.restore(sess, 'checkpoints/______.ckpt')
    counter = 0
    for e in range(epochs):
        # Train network
        new_state = sess.run(model.initial_state)
        loss = 0
        for x, y in get_batches(encoded, batch_size, num_steps):
            counter += 1
            start = time.time()
            feed = {model.inputs: x,
                    model.targets: y,
                    model.keep_prob: keep_prob,
                    model.initial_state: new_state}
            batch_loss, new_state, _ = sess.run([model.loss, 
                                                 model.final_state, 
                                                 model.optimizer], 
                                                 feed_dict=feed)
            if (counter % print_every_n == 0):
                end = time.time()
                print('Epoch: {}/{}... '.format(e+1, epochs),
                      'Training Step: {}... '.format(counter),
                      'Training loss: {:.4f}... '.format(batch_loss),
                      '{:.4f} sec/batch'.format((end-start)))
        
            if (counter % save_every_n == 0):
                saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))
    
    saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))

---------------------------------------------------
<def build_output>
------------------
lstm_output.shape =  (200, 100, 512)
seq_output.shape  =  (200, 100, 512)
x.shape           =  (20000, 512)
softmax_w.shape   =  (512, 83)
softmax_b.shape   =  (83,)
logits.shape      =  (20000, 83)
out.shape         =  (20000, 83)
------------------
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.

---------------------------------------------------
<def build_loss>
------------------
y_one_hot.shape    =  (200, 100, 83)
y_reshaped.shape   =  (20000, 83)
logits.get_shape() =  (20000, 83)
loss.shape         =  ()
------------------
Epoch: 1/20...  Training Step: 50...  Training loss: 3.1684...  0.3994 sec/batch
Epoch: 2/20...  Training Step: 100...  Training loss: 3.1403...  0.3042 sec/batch
Epoch: 2/20...  Training Step: 150...  Training loss: 2.7312...  0.

#### Saved checkpoints

Read up on saving and loading checkpoints here: https://www.tensorflow.org/programmers_guide/variables

In [18]:
tf.train.get_checkpoint_state('checkpoints')

model_checkpoint_path: "checkpoints\\i1980_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i200_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i400_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i600_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i800_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1000_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1200_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1400_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1600_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1800_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1980_l512.ckpt"

## Sampling

Now that the network is trained, we'll can use it to generate new text. The idea is that we pass in a character, then the network will predict the next character. We can use the new one, to predict the next one. And we keep doing this to generate all new text. I also included some functionality to prime the network with some text by passing in a string and building up a state from that.

The network gives us predictions for each character. To reduce noise and make things a little less random, I'm going to only choose a new character from the top N most likely characters.



In [38]:
def pick_top_n(preds, vocab_size, top_n=5):
    # 不要な次元を削除する 例えば、(3,1) => (3,)
    p = np.squeeze(preds)
    
    # argsortで、昇順に並べ替えたインデックス配列(ndarray)を取得
    # top_n 以外の確率を 0 と　みなすために　インデックスを取得
    index_to_be_zero = np.argsort(p)[:-top_n]
    p[index_to_be_zero] = 0
    
    # top_n　のみで確率を再計算する
    p = p / np.sum(p)
    
    # top_n から random　に　1個取得
    # 出力：size=1 の配列 -> [0]　で　スカラを取得 
    c = np.random.choice(vocab_size, 1, p=p)[0]
    
    return c

In [73]:
def sample(checkpoint, n_samples, lstm_size, vocab_size, prime="The "):
    # 先頭の文字列を配列に代入
    samples = [c for c in prime]
    
    # LSTM用インスタンスの作成
    model   = CharRNN(len(vocab), lstm_size=lstm_size, sampling=True)
    
    # 保存用インスタンスの作成
    saver   = tf.train.Saver()
    
    with tf.Session() as sess:
        # check point の読み込み
        saver.restore(sess, checkpoint)
        
        # session　の初期化
        new_state = sess.run(model.initial_state)
        
        #------------------------------------------------------#
        # ユーザー入力に対する処理
        for char_input in prime:
            
            # run 用の入力を作成
            x      = np.zeros((1, 1))
            x[0,0] = vocab_to_int[char_input]
            feed   = {model.inputs        : x,
                      model.keep_prob     : 1.,
                      model.initial_state : new_state}
            
            # run の実行
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)
        
        #------------------------------------------------------#
        # ユーザー入力 + 1　のデータを保存
        char_id_output = pick_top_n(preds, len(vocab))
        samples.append(int_to_vocab[char_id_output])

        #------------------------------------------------------#
        # ユーザー入力以降のデータ処理
        char_id_input = char_id_output
        #
        for i in range(n_samples):
            
            # run 用の入力を作成
            x[0,0] = char_id_input
            
            feed   = {model.inputs        : x,
                      model.keep_prob     : 1.,
                      model.initial_state : new_state}
            
            # run の実行
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)
            
            # 予測結果から、ランダムに出力を1個取得
            char_id_output = pick_top_n(preds, len(vocab))
            
            # 出力用のリストにデータを保存
            samples.append(int_to_vocab[char_id_output])
            print("input = ", int_to_vocab[char_id_input], " : output = ", int_to_vocab[char_id_output])
            
            # 次のループのために、入力＝出力とする
            char_id_input = char_id_output
        #------------------------------------------------------#
        
    return ''.join(samples)

Here, pass in the path to a checkpoint and sample from the network.

In [74]:
tf.train.latest_checkpoint('checkpoints')

'checkpoints\\i1980_l512.ckpt'

In [75]:
checkpoint = tf.train.latest_checkpoint('checkpoints')
samp = sample(checkpoint, 2000, lstm_size, len(vocab), prime="Far")
print(samp)

---------------------------------------------------
<def build_output>
------------------
lstm_output.shape =  (1, 1, 512)
seq_output.shape  =  (1, 1, 512)
x.shape           =  (1, 512)
softmax_w.shape   =  (512, 83)
softmax_b.shape   =  (83,)
logits.shape      =  (1, 83)
out.shape         =  (1, 83)
------------------
---------------------------------------------------
<def build_loss>
------------------
y_one_hot.shape    =  (1, 1, 83)
y_reshaped.shape   =  (1, 83)
logits.get_shape() =  (1, 83)
loss.shape         =  ()
------------------
INFO:tensorflow:Restoring parameters from checkpoints\i1980_l512.ckpt
input =  d  : output =  l
input =  l  : output =  i
input =  i  : output =  o
input =  o  : output =  n
input =  n  : output =  .
input =  .  : output =  

input =  
  : output =  T
input =  T  : output =  h
input =  h  : output =  i
input =  i  : output =  s
input =  s  : output =   
input =     : output =  w
input =  w  : output =  o
input =  o  : output =  r
input =  r  : output

input =     : output =  w
input =  w  : output =  a
input =  a  : output =  l
input =  l  : output =  k
input =  k  : output =  e
input =  e  : output =  d
input =  d  : output =  ,
input =  ,  : output =   
input =     : output =  w
input =  w  : output =  i
input =  i  : output =  t
input =  t  : output =  h
input =  h  : output =   
input =     : output =  t
input =  t  : output =  h
input =  h  : output =  e
input =  e  : output =   
input =     : output =  p
input =  p  : output =  r
input =  r  : output =  i
input =  i  : output =  n
input =  n  : output =  c
input =  c  : output =  e
input =  e  : output =  s
input =  s  : output =  s
input =  s  : output =   
input =     : output =  w
input =  w  : output =  a
input =  a  : output =  s
input =  s  : output =   
input =     : output =  s
input =  s  : output =  u
input =  u  : output =  c
input =  c  : output =  h
input =  h  : output =  

input =  
  : output =  a
input =  a  : output =  t
input =  t  : output =   
input =     

input =  s  : output =  w
input =  w  : output =  e
input =  e  : output =  r
input =  r  : output =  i
input =  i  : output =  n
input =  n  : output =  g
input =  g  : output =   
input =     : output =  L
input =  L  : output =  e
input =  e  : output =  v
input =  v  : output =  i
input =  i  : output =  n
input =  n  : output =   
input =     : output =  s
input =  s  : output =  t
input =  t  : output =  a
input =  a  : output =  r
input =  r  : output =  t
input =  t  : output =  i
input =  i  : output =  n
input =  n  : output =  g
input =  g  : output =  l
input =  l  : output =  y
input =  y  : output =   
input =     : output =  a
input =  a  : output =  n
input =  n  : output =  d
input =  d  : output =   
input =     : output =  h
input =  h  : output =  a
input =  a  : output =  p
input =  p  : output =  p
input =  p  : output =  y
input =  y  : output =   
input =     : output =  t
input =  t  : output =  o
input =  o  : output =   
input =     : output =  h
input =  h  

input =  a  : output =  n
input =  n  : output =  d
input =  d  : output =   
input =     : output =  t
input =  t  : output =  h
input =  h  : output =  a
input =  a  : output =  t
input =  t  : output =   
input =     : output =  t
input =  t  : output =  h
input =  h  : output =  e
input =  e  : output =   
input =     : output =  d
input =  d  : output =  o
input =  o  : output =  c
input =  c  : output =  t
input =  t  : output =  o
input =  o  : output =  r
input =  r  : output =  s
input =  s  : output =   
input =     : output =  h
input =  h  : output =  a
input =  a  : output =  d
input =  d  : output =   
input =     : output =  b
input =  b  : output =  e
input =  e  : output =  e
input =  e  : output =  n
input =  n  : output =   
input =     : output =  a
input =  a  : output =  t
input =  t  : output =   
input =     : output =  t
input =  t  : output =  h
input =  h  : output =  e
input =  e  : output =   
input =     : output =  p
input =  p  : output =  e
input =  e  

input =  s  : output =  t
input =  t  : output =  u
input =  u  : output =  c
input =  c  : output =  h
input =  h  : output =  .
input =  .  : output =   
input =     : output =  H
input =  H  : output =  e
input =  e  : output =   
input =     : output =  w
input =  w  : output =  a
input =  a  : output =  s
input =  s  : output =   
input =     : output =  a
input =  a  : output =   
input =     : output =  l
input =  l  : output =  i
input =  i  : output =  t
input =  t  : output =  t
input =  t  : output =  l
input =  l  : output =  e
input =  e  : output =   
input =     : output =  a
input =  a  : output =  r
input =  r  : output =  r
input =  r  : output =  a
input =  a  : output =  c
input =  c  : output =  e
input =  e  : output =  s
input =  s  : output =  ,
input =  ,  : output =  

input =  
  : output =  a
input =  a  : output =  n
input =  n  : output =  d
input =  d  : output =   
input =     : output =  t
input =  t  : output =  h
input =  h  : output =  e
input =  e  

input =  l  : output =   
input =     : output =  c
input =  c  : output =  a
input =  a  : output =  n
input =  n  : output =  c
input =  c  : output =  a
input =  a  : output =  l
input =  l  : output =  e
input =  e  : output =   
input =     : output =  y
input =  y  : output =  o
input =  o  : output =  u
input =  u  : output =  r
input =  r  : output =   
input =     : output =  f
input =  f  : output =  i
input =  i  : output =  n
input =  n  : output =  d
input =  d  : output =   
input =     : output =  s
input =  s  : output =  u
input =  u  : output =  p
input =  p  : output =  p
input =  p  : output =  o
input =  o  : output =  r
input =  r  : output =  t
input =  t  : output =  ,
input =  ,  : output =  "
input =  "  : output =   
input =     : output =  s
input =  s  : output =  h
input =  h  : output =  e
input =  e  : output =   
input =     : output =  t
input =  t  : output =  h
input =  h  : output =  o
input =  o  : output =  u
input =  u  : output =  g
input =  g  

input =  r  : output =  i
input =  i  : output =  v
input =  v  : output =  e
input =  e  : output =   
input =     : output =  i
input =  i  : output =  n
input =  n  : output =  

input =  
  : output =  t
input =  t  : output =  h
input =  h  : output =  e
input =  e  : output =  r
input =  r  : output =  e
input =  e  : output =  ,
input =  ,  : output =   
input =     : output =  t
input =  t  : output =  h
input =  h  : output =  a
input =  a  : output =  t
input =  t  : output =   
input =     : output =  I
input =  I  : output =   
input =     : output =  h
input =  h  : output =  a
Fardlion.
This work were deally af that was never filled by her house. The
still shild a door was so always to his hands, he was delighted to
say. He had to be contractiously and all that would be suck a leating
of a condinion of the dissuct of the people who had been a criticition
of his whole and all a satideaty walked, with the princess was such
at their hall tor trouble their court. He was signi

In [69]:
checkpoint = 'checkpoints/i200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

---------------------------------------------------
<def build_output>
------------------
lstm_output.shape =  (1, 1, 512)
seq_output.shape  =  (1, 1, 512)
x.shape           =  (1, 512)
softmax_w.shape   =  (512, 83)
softmax_b.shape   =  (83,)
logits.shape      =  (1, 83)
out.shape         =  (1, 83)
------------------
---------------------------------------------------
<def build_loss>
------------------
y_one_hot.shape    =  (1, 1, 83)
y_reshaped.shape   =  (1, 83)
logits.get_shape() =  (1, 83)
loss.shape         =  ()
------------------
INFO:tensorflow:Restoring parameters from checkpoints/i200_l512.ckpt
prime =  Far  : c =  F
prime =  Far  : c =  a
prime =  Far  : c =  r
c       =  60
samples =  ['F', 'a', 'r', 'd']
input =  e  : output =  e
input =     : output =   
input =  s  : output =  s
input =  i  : output =  i
input =  n  : output =  n
input =  s  : output =  s
input =  s  : output =  s
input =     : output =   
input =  t  : output =  t
input =  e  : output =  e
input =   

input =  w  : output =  w
input =  h  : output =  h
input =  a  : output =  a
input =  t  : output =  t
input =     : output =   
input =  w  : output =  w
input =  h  : output =  h
input =  o  : output =  o
input =     : output =   
input =  t  : output =  t
input =  h  : output =  h
input =  i  : output =  i
input =  t  : output =  t
input =     : output =   
input =  w  : output =  w
input =  a  : output =  a
input =  t  : output =  t
input =     : output =   
input =  o  : output =  o
input =  n  : output =  n
input =  d  : output =  d
input =     : output =   
input =  w  : output =  w
input =  e  : output =  e
input =  t  : output =  t
input =     : output =   
input =  w  : output =  w
input =  h  : output =  h
input =  e  : output =  e
input =     : output =   
input =  t  : output =  t
input =  h  : output =  h
input =  e  : output =  e
input =  r  : output =  r
input =  e  : output =  e
input =     : output =   
input =  a  : output =  a
input =  d  : output =  d
input =     

input =  t  : output =  t
input =  e  : output =  e
input =     : output =   
input =  t  : output =  t
input =  o  : output =  o
input =  u  : output =  u
input =  t  : output =  t
input =     : output =   
input =  h  : output =  h
input =  a  : output =  a
input =     : output =   
input =  s  : output =  s
input =  e  : output =  e
input =     : output =   
input =  w  : output =  w
input =  a  : output =  a
input =  s  : output =  s
input =  s  : output =  s
input =  i  : output =  i
input =  n  : output =  n
input =     : output =   
input =  s  : output =  s
input =  o  : output =  o
input =  s  : output =  s
input =     : output =   
input =  a  : output =  a
input =  n  : output =  n
input =  d  : output =  d
input =     : output =   
input =  t  : output =  t
input =  o  : output =  o
input =  r  : output =  r
input =     : output =   
input =  w  : output =  w
input =  h  : output =  h
input =  i  : output =  i
input =  m  : output =  m
input =     : output =   
input =  t  

input =  n  : output =  n
input =     : output =   
input =  s  : output =  s
input =  a  : output =  a
input =  s  : output =  s
input =     : output =   
input =  a  : output =  a
Farde sinss te wo wis sot the
sadinte sas tasese sas tat ing whas was athe we th an thing ass at ifin his hat thint werit aresind hathe tard wore ho serer sethan arse he sond wathe sat hes at toed ter ant the sind was wo he silles on as wothe thet al on he had and she worigg oos ale tor out th wete to the sot the son het what who thit wat ond wet whe there ad wor hed tort tha sos oring ot ho san ar and thas as he tined sothe tetises an th wind angithe tond as hire tithe ha dederens wot an ase toterent arthe wot her hos an thet wat he sho wins toreresig ofrind
tone and was an thas soss ont ant on thin ange whes, se selin te se tit hath and and
ounte tout ha se wassin sos and tor whim tere tir ho wan atha his tar sot hes alled she te sas ile
tore the he seres had winger al the sele tho were he toun sar withe 

In [24]:
checkpoint = 'checkpoints/i600_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

---------------------------------------------------
<def build_output>
------------------
lstm_output.shape =  (1, 1, 512)
seq_output.shape  =  (1, 1, 512)
x.shape           =  (1, 512)
softmax_w.shape   =  (512, 83)
softmax_b.shape   =  (83,)
logits.shape      =  (1, 83)
out.shape         =  (1, 83)
------------------
---------------------------------------------------
<def build_loss>
------------------
y_one_hot.shape    =  (1, 1, 83)
y_reshaped.shape   =  (1, 83)
logits.get_shape() =  (1, 83)
loss.shape         =  ()
------------------
INFO:tensorflow:Restoring parameters from checkpoints/i600_l512.ckpt
Farlry a she cale, to his shard
were, this
sher and were a siself aster,.

"Where wele him talk," and wert
her, she was bread the said, but that seeped if it's
seathere, the
sear to he sore at his tooter, with him, but souned to the pars to as the dingress to shome her soming instions the collised and his was ont
sindion that the centirassed in the pirte the comparion. I's cane to s

In [25]:
checkpoint = 'checkpoints/i1200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

---------------------------------------------------
<def build_output>
------------------
lstm_output.shape =  (1, 1, 512)
seq_output.shape  =  (1, 1, 512)
x.shape           =  (1, 512)
softmax_w.shape   =  (512, 83)
softmax_b.shape   =  (83,)
logits.shape      =  (1, 83)
out.shape         =  (1, 83)
------------------
---------------------------------------------------
<def build_loss>
------------------
y_one_hot.shape    =  (1, 1, 83)
y_reshaped.shape   =  (1, 83)
logits.get_shape() =  (1, 83)
loss.shape         =  ()
------------------
INFO:tensorflow:Restoring parameters from checkpoints/i1200_l512.ckpt
Farlen the simply tow home of the carriage,
and stonged to him that as at at a marshine was handsing his
his hat and the midute, he had never, hor if the
strigh of the more whice and still he husbaded was strangly soming about
the mindit of the sawe was on the
contembors of sime that
was is toot her somorion, and the satical on that starling of the same
tign on a sort of a chulce, 